### ISSUE TITLE
npx browserslist@latest --update-db

### ISSUE THREAD

**Issue by nickzoic** [VariantEffect/mavedb-ui#107]
When I run `npm run build` it [complains](https://github.com/VariantEffect/mavedb-ui/actions/runs/7565195748/job/20600556976#step:5:9)  (many times):
```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
on the other hand, when I add that step in it still [complains (once)](https://github.com/VariantEffect/mavedb-ui/actions/runs/7564841555/job/20599619647#step:5:5)
```
npx: installed 7 in 1.067s
The --update-db command is deprecated.
Please use npx update-browserslist-db@latest instead.
Browserslist DB update will still be made.
Latest version:     1.0.30001578
Installed version:  1.0.30001332
```
I have no idea what that means so I'm adding it as an issue.  Do we just need to update the locked version of `caniuse-lite`, whatever that is?

**Comment by bencap** [comment]
Closing, as this particular issue doesn't seem to appear anymore.
