### ISSUE TITLE
Clear button throws error Uncaught (in promise) TypeError: Cannot read properties of null (reading 'UniProt')

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-ui#109]
If only typing something in short description of creating a new score set and clicking Clear button, Clear button won't work and will throw an error Uncaught (in promise) TypeError: Cannot read properties of null (reading 'UniProt') from 
```
'targetGene.externalIdentifiers': {
      deep: true,
      handler: function (newValue) {
        // If an identifier has been set, set the offset to 0 by default.
        for (const dbName of externalGeneDatabases) {
          // Error is from this line
          if (newValue[dbName]?.identifier?.identifier != null && newValue[dbName]?.offset == null) {
            this.targetGene.externalIdentifiers[dbName].offset = 0
          }
        }
      }
    },
    
```
But clicking Clear button again, it'll work.

**Comment by EstelleDa** [comment]
In Mavedb website, after clicking the Clear button in creating a new score set, Target Sequence and Genomic Coordinates totally disappear.

**Comment by bencap** [comment]
Completed via #113.
