### ISSUE TITLE
any validation errors prevent all future submits for 'New score set' and 'New experiment'

### ISSUE THREAD

**Issue by ashsny** [VariantEffect/mavedb-ui#115]
steps to replicate:
1. log in
2. open 'New experiment' page
3. click 'Save'
4. four fields marked 'Required' (expected)
5. fill out those fields
6. click 'Save'

expected: save occurs 
actual: save not attempted

this bug is not present on the `main` branch/mavedb.org, but is present on the `release-2023.5.0` branch. it is currently blocking the release of that branch.

as a result of upgrading the `vee-validate` package on branch `release-2023.5.0`, the behavior of `setValidationErrors({})` has changed (see `vee-validate` documentation [here](https://vee-validate.logaretm.com/v4/api/use-form/#composable-api))

relevantly:
![image](https://github.com/VariantEffect/mavedb-ui/assets/1389678/8adbf5ed-ae94-4f63-a14c-b70fd87782f7)

the effect of this is that our code no longer clears server side errors before checking and blocking save if there are any errors, so all saves are blocked forever if any server-side validation errors occur.

I will use this an an opportunity to extract `vee-validate` from `ExperimentEditor` and `ScoreSetEditor` as we are not using any functionality of the package and are only using it to set and clear fields on a reactive object. it is no longer performing that task adequately.

**Comment by bencap** [comment]
Completed via #116.
