### ISSUE TITLE
Autocomplete for publications is broken.

### ISSUE THREAD

**Issue by ashsny** [VariantEffect/mavedb-ui#119]
steps to reproduce:
1. log in, go to 'new experiment'
2. enter '5' in 'DOI' Identifiers

expected: autocomplete dropdown with publications
got: nothing, spinner in form
console has `Loaded 27 items from https://api.mavedb.org/api/v1/doi-identifiers/` so the the API call itself seems to be working, but nothing is displayed in the front end

**Comment by EstelleDa** [comment]
I switch to main branch and update it, then run `MODE=live npm run dev`. Both DOI and Publication Identifiers work.

**Comment by EstelleDa** [comment]
It's very weird. I rebuilt Docker server, updated both API and UI branches. Both DOI and PubMed ID work in local database, but the https://www.mavedb.org/#/create-experiment is indeed NOT working. Same problem as the description.

**Comment by ashsny** [comment]
fixed by pushing a new build to mavedb.org - it appears the breakage happens between the currently checked in package.lock and one generated by `rm package.lock && npm install` not sure what package broke as the relevant ones seem to be pinned
