### ISSUE TITLE
DOIs and PubMed accept new value functions don't work

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-ui#120]
Both ScoreSetEditor.vue and ExperimentEditor.vue have this error. 
Typing new value in both DOIs and PubMed IDs gets error `Uncaught TypeError: (input.modelValue || "").trim is not a function`

It's in acceptNewDoiIdentifier and acceptNewPublicationIdentifier functions. 

The codes we used before were similar like this
```
const input = this.$refs.xxInput
const searchText = (input.inputTextValue || '').trim() 
or
const searchText = (input.value || '').trim()  
```
It worked before, but later not working.

This kind also worked before and now only works 1 out of about 30 times trials. (In fact, I only tried it in Taxonomy not DOI, but not confused others so use same example codes.)
```
<html> ... <autocomplete v-model='doiIdentifiers'>... </html>
const searchText = (this.doiIdentifiers && this.doiIdentifiers.trim) ? this.doiIdentifiers.trim() : ''
```

My understanding of Vue is that we can use this.$refs.xxInput and this.v-model to get value directly. However, it seems these two don't work.

**Comment by ashsny** [comment]
I can't reproduce the problem you describe on mavedb.org. where is it occurring for you? are you using the checked-in package.lock as I mentioned in #119?

**Comment by EstelleDa** [comment]
Page https://mavedb.org/#/create-score-set and https://mavedb.org/#/create-experiment have this problem. 
For example:
1. log in, go to ‘new score set’
2. enter ‘10.1003/jimd.12223’ in ‘DOI’ Identifiers (10.1003/jimd.12223 is not present in our database)
3. press Enter/Return button
