### ISSUE TITLE
The clear button only appears when users type something in searching box

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-ui#121]
In https://mavedb.org/#/search page:
If users choose any filter condition in target name, target type, target organism and target accession, none of any clear button allows them to clean these keywords they chose. 

The Clear All button only appears when users type something in the middle top of Search box. 
<img width="1211" alt="image" src="https://github.com/VariantEffect/mavedb-ui/assets/8445097/f16caa62-6496-4d34-94f7-058528aa8f8e">

**Comment by bencap** [comment]
Released in https://github.com/VariantEffect/mavedb-ui/releases/tag/v2024.1.1
