### ISSUE TITLE
Improved login mechanism

### ISSUE THREAD

**Issue by jstone-uw** [VariantEffect/mavedb-ui#135]
**Issues**
- Users report getting logged out and not being able to log in immediately.
- When using multiple tabs, users must log in separately in each tab.
- The login mechanism requires a popup window.

Some of these issues may inhere in the choice of ORCID for login, the use of OpenID Connect (OIDC) as a mechanism, or the particular OIDC library we're using now.

**Comment by bencap** [comment]
Released in https://github.com/VariantEffect/mavedb-api/releases/tag/v2024.1.0
