### ISSUE TITLE
possible to upload Score Set without Target sequence

### ISSUE THREAD

**Issue by PlushZ** [VariantEffect/mavedb-ui#142]
Example https://www.mavedb.org/#/score-sets/tmp:540c9d47-9e0c-4c56-839c-3b1249a957df
I assume, it's a bug and MaveDB should not allow to upload scoreset without attached target sequence.

**Comment by EstelleDa** [comment]
I suppose it's a bug. I think users should attach either target sequence or genomic coordinates when they create a new score set. Now MaveDB doesn't have any actual validator to check it if target section is empty.

**Comment by EstelleDa** [comment]
Pull request is https://github.com/VariantEffect/mavedb-api/pull/166. Original codes got some problems so they don't work correctly.

**Comment by bencap** [comment]
[Debug creating and editing score set without target sequence or accession problem VariantEffect/mavedb-api#166](https://github.com/VariantEffect/mavedb-api/pull/166) This change fixes this issue as written, but it is still possible for users to create a score set without any targets. Doing that also doesn't make sense, but can be handled as a [separate issue](https://github.com/VariantEffect/mavedb-api/issues/177).
