### ISSUE TITLE
Variant search

### ISSUE THREAD

**Issue by jstone-uw** [VariantEffect/mavedb-ui#164]
On the score set screen, users should be able to search for variants.

The result of a search should be a list of matching variants, allowing the user to navigate to a variant screen. (See #165.)

Since we do not yet have variants mapped to reference genomes, search will occur only in the scope of an individual score set, and coordinates will be relative to its target gene(s).

**Comment by jstone-uw** [comment]
Search input remains to be determined.
- MaveHGVS strings
  - We should probably not require a target gene to be specified, and a given HGVS string might match variants in multiple targets.
  - Shall we expand search result to include all multiple-mutation variants that include the given variation(s)?
- Offsets?

Users should also be able to select a variant by clicking on the heatmap of single-AA variants.

**Comment by bencap** [comment]
Released in https://github.com/VariantEffect/mavedb-api/releases/tag/v2024.1.0
