### ISSUE TITLE
Link to UCSC Genome Browser

### ISSUE THREAD

**Issue by jstone-dev** [VariantEffect/mavedb-ui#189]
- Host MaveDB track data on S3.
- On the MaveDB homepage or another suitable place, add a link to the UCSC Genome Browser with this track data.

This is needed to support a Wagner lab publication. We may later want to add genome browser links to individual score sets.

**Comment by jstone-uw** [comment]
- Hosting track data has been deferred. The tracks may be updated for a while, but in the near future we'll likely host them in the MaveDB AWS environment.
- Instead of one link from the homepage, we're going to go ahead and add genome browser links to individual score sets. These links have been provided.

**Comment by jstone-uw** [comment]
**Notes on the data model**

- One suggested approach was to add a table for external links with a many-to-one relationship to score sets. Each row would have a site name or link type (e.g. "UCSC Genome Browser") and a URL.
- On the other hand, we could just add a column like `ucsc_genome_browser_url` to the score sets table.

The latter option seems too specific when we know we're likely to add more links. But I'm not sure it's worth adding table relationships for this yet, so I've opted to add a JSONB column to the score sets table. This is the intended usage of the new `external_links` column:

```
{
  "ucscGenomeBrowser": {
    "url": "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr17:43051063-43051117&hubUrl=https://public.gi.ucsc.edu/~cline/mavedb/hub/hub.txt&Variant_Effect_Maps_hideKids=1&BRCA1_00000097-s-1=dense"
  }
}
```

That is, it's an object whose keys identify the target site or service. The values are objects that currently only include URLs, but we can add metadata as necessary later. On the API side, the structure above is exposed and enforced by explicit Pedantic models.

**Comment by bencap** [comment]
Completed via #208.
