### ISSUE TITLE
'Send to Galaxy' in ScoreSet view is broken

### ISSUE THREAD

**Issue by PlushZ** [VariantEffect/mavedb-ui#207]
Changes made in https://github.com/VariantEffect/mavedb-ui/pull/85 are not working now.
Galaxy opens MaveDB by https://mavedb.org/#/?galaxyUrl=X&toolID=Y&requestFromGalaxy=Z. Parameters passing in url from Galaxy are lost.

**Comment by bencap** [comment]
Fixed via #218.
