### ISSUE TITLE
Request user email address on registration

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#21]
In the Django version of MaveDB, users can set their email address in their profile and we can also access a user's public email address via ORCID (which most people have not set).

Users should be prompted to provide their email address when they log in for the first time, and we should consider adding an unobtrusive banner/box at the top of the user's profile if they don't have one set.

**Comment by jstone-uw** [comment]
We've discussed three possible prompts:

1. A prompt after first login
2. A notice at the top of the screen for users who haven't set their email address
3. A required prompt for users who create experiments or score sets.

If the purpose is to allow communication with people who have uploaded data, then maybe a combination of #1 and #3 is sufficient. What do others think?

**Comment by bencap** [comment]
Released in https://github.com/VariantEffect/mavedb-api/releases/tag/v2024.1.0
