### ISSUE TITLE
Heatmap is not shown for score sets with genomic targets.

### ISSUE THREAD

**Issue by jstone-uw** [VariantEffect/mavedb-ui#215]
**Steps to reproduce**

1. Visit https://mavedb.org/score-sets/urn:mavedb:00000097-a-1 (BRCA1 SGE Exon 2 Replicate 1) or https://mavedb.org/score-sets/urn:mavedb:00000097-0-1 (BRCA1 SGE normalized scores for all exons).

**Comment by EstelleDa** [comment]
@jstone-uw 
An example of hgvs_pro of urn:mavedb:00000097-a-1 is NP_009225.1:p.Cys27Gly that leads to function `parseSimpleProVariant` from lib/mave-hgvs.ts can't match variant and return null back. 
@afrubin Is this a correct format of hgvs_pro?
