### ISSUE TITLE
"Create a new score set" target screen

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#220]
When creating a new target, it's not super clear to the user which fields are optional and which are required. If some required information is not filled out, the current behavior is to just not allow the target to be created with no message (clicking the "Add Target" button appears to do nothing).

Required items like the taxonomy (this is what tripped up me and the user I was helping) should be more clearly flagged as required.

If possible, fields that are responsible for not progressing should be highlighted or otherwise identified when the user clicks "Add Target".

**Comment by bencap** [comment]
Should be addressed as part of #214.

**Comment by bencap** [comment]
Closing, addressed by #214.
