### ISSUE TITLE
Number of variants on score set page

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#222]
I think we include this value in the API, but we don't actually display the number of variants on the score set page. It should be included, maybe at the top of the Variants section above the preview table. If nothing else, it's a useful sanity check/reassurance for people who have just uploaded a dataset.

We can add additional variant-related statistics (like coverage, number of missense/synonymous/nonsense for coding, etc.) to this section later on.

**Comment by bencap** [comment]
Closing in favor of #35
