### ISSUE TITLE
'Next' button of score set creation wizard not visible on thin windows

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-ui#227]
On thin windows the 'next' button for the creation wizard is not visible and you cannot advance through the creation steps.

To reproduce:
- navigate to https://www.mavedb.org/create-score-set
- make your window smaller, until the button disapears

Desired behavior: Button is always visible like the Save, Clear, and Cancel buttons.

(Chrome Version 126.0.6478.127)

**Comment by EstelleDa** [comment]
My Safari and Chrome get the same problem. It's an interesting bug. Page can scroll up and down, but not right or left.
