### ISSUE TITLE
Unable to update an existing scoreset 

### ISSUE THREAD

**Issue by kaiyuegithub** [VariantEffect/mavedb-ui#238]
I was trying to update the scores in an existing scoreset.
However it gives error at the final step.
![image](https://github.com/user-attachments/assets/6a1aef4f-9624-44a7-a6d3-d176b08849fa)

The dataset format was the same as before.
The target was copied from an existing target.

**Comment by EstelleDa** [comment]
Hi @kaiyuegithub, did you add one more target when you updated the existing score set?

**Comment by kaiyuegithub** [comment]
Hi,
No, I  only used the same target as before. 
I tried either adding the target myself or using the function of copying it from an existing target (that I created). 
Neither worked

**Comment by kaiyuegithub** [comment]
Sure!
The existing dataset was https://www.mavedb.org/score-sets/urn:mavedb:00001197-a-
Here is the sequence and the file:

>FKRP
ATGCGGCTCACCCGCTGCCAGGCTGCCCTGGCGGCCGCCATCACCCTCAACCTTCTGGTCCTCTTCTATGTCTCGTGGCT
GCAGCACCAGCCTAGGAATTCCCGGGCCCGGGGGCCCCGTCGTGCCTCTGCTGCCGGCCCCCGTGTCACCGTCCTGGTGC
GGGAGTTCGAGGCATTTGACAACGCGGTGCCCGAGCTGGTAGACTCCTTCCTGCAGCAAGACCCAGCCCAGCCCGTGGTG
GTGGCAGCCGACACGCTCCCCTACCCGCCCCTGGCCCTGCCCCGCATCCCCAACGTGCGTCTGGCGCTGCTCCAGCCCGC
CCTGGACCGGCCAGCCGCAGCCTCGCGCCCGGAGACCTACGTGGCCACCGAGTTTGTGGCCCTAGTACCTGATGGGGCGC
GGGCTGAGGCACCTGGCCTGCTGGAGCGCATGGTGGAGGCGCTCCGCGCAGGAAGCGCACGTCTGGTGGCCGCCCCGGTT
GCCACGGCCAACCCTGCCAGGTGCCTGGCCCTGAACGTCAGCCTGCGAGAGTGGACCGCCCGCTATGGCGCAGCCCCCGC
CGCGCCCCGCTGCGACGCCCTGGACGGAGATGCTGTGGTGCTCCTGCGCGCCCGCGACCTCTTCAACCTCTCGGCGCCCC
TGGCCCGGCCGGTGGGCACCAGCCTCTTTCTGCAGACCGCCCTTCGCGGCTGGGCGGTGCAGCTGCTGGACTTGACCTTC
GCCGCGGCGCGCCAGCCCCCGCTGGCCACGGCCCACGCGCGCTGGAAGGCTGAGCGCGAGGGACGCGCTCGGCGGGCGGC
GCTGCTCCGCGCGCTGGGCATCCGCCTAGTGAGCTGGGAAGGCGGGCGGCTGGAGTGGTTCGGCTGCAACAAGGAGACCA
CGCGCTGCTTCGGAACCGTGGTGGGCGACACGCCCGCCTACCTCTACGAGGAGCGCTGGACGCCCCCCTGCTGCCTGCGC
GCGCTGCGCGAGACCGCCCGCTATGTGGTGGGCGTGCTGGAGGCTGCGGGCGTGCGCTACTGGCTCGAGGGCGGCTCACT
GCTGGGGGCCGCCCGCCACGGGGACATCATCCCATGGGACTACGACGTGGACCTGGGCATCTACTTGGAGGACGTGGGCA
ACTGCGAGCAGCTGCGGGGGGCAGAGGCCGGCTCGGTGGTGGATGAGCGCGGCTTCGTATGGGAGAAGGCGGTCGAGGGC
GACTTTTTCCGCGTGCAGTACAGCGAAAGCAACCACTTGCACGTGGACCTGTGGCCCTTCTACCCCCGCAATGGCGTCAT
GACCAAGGACACGTGGCTGGACCACCGGCAGGATGTGGAGTTTCCCGAGCACTTCCTGCAGCCGCTGGTGCCCCTGCCCT
TTGCCGGCTTCGTGGCGCAGGCGCCTAACAACTACCGCCGCTTCCTGGAGCTCAAGTTCGGGCCCGGGGTCATCGAGAAC
CCCCAGTACCCCAACCCGGCACTGCTGAGTCTGACGGGAAGCGGC

[FKRP_mavedb_0729.csv](https://github.com/user-attachments/files/16407379/FKRP_mavedb_0729.csv)

**Comment by EstelleDa** [comment]
Thanks Kaiyue!

**Comment by EstelleDa** [comment]
Hi kaiyue @kaiyuegithub , I don't get any error including the editing score set. Is there any difference from yours in the below steps?
My steps are:
1. Choose FKRP in target gene part.
2. Upload your sequence and choose DNA.
3. Click Add Target button.
4. Upload your score file.
5. Finally click Save Changes button or Save button. 
<img width="573" alt="image" src="https://github.com/user-attachments/assets/83f1f430-55de-47a0-81a5-cb86c4b9bcfb">

**Comment by kaiyuegithub** [comment]
I don't see any difference from what I did.
Just to add more context, before the first step you listed, I selected "Yes, this supersedes another score set" and picked the existing dataset.

**Comment by kaiyuegithub** [comment]
The existing dataset was 
https://www.mavedb.org/score-sets/urn:mavedb:00001197-a-1

**Comment by EstelleDa** [comment]
Yes, I get the same error if I choose a supersede score set.

**Comment by EstelleDa** [comment]
Hi Kaiyue, I fixed the bug and await my teammate to deploy it to the MaveDB. I'll let you know when the new MaveDB works.
