### ISSUE TITLE
Clicking 'Clear Keywords' in the Experiment Editor Resets Keywords to the Original State

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-ui#299]
To reproduce:
- Create an experiment with keywords
- Edit the experiment
- Attempt to clear keywords (they will not clear)
- Change a keyword
- Attempt to clear keywords (they will reset to their original state)

The keyword behavior should be to properly clear when clicking the clear keywords button.

**Comment by EstelleDa** [comment]
In editing the experiment and score set page, both of their clear buttons are resetting to the original state. Only in creating page, the clear buttons are total clear the data.
