### ISSUE TITLE
Data licenses not displayed

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#34]
I checked the production deployment of the new site and I didn’t see the logo for the dataset license on the score set pages. Is this missing from the UI or did something go wrong with the migration?

**Comment by jstone-uw** [comment]
Yep, they've never been displayed on the new site's score set pages. This is one of the issues I have on a list to address this week, though.

**Comment by jstone-uw** [comment]
I've added them, though, and will see if I can make the display prettier tomorrow.

**Comment by afrubin** [comment]
I can see them now, thanks for the quick fix @jstone-uw! Making it prettier can wait until the UI refresh.
