### ISSUE TITLE
Metadata fields not saving properly?

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#43]
A user reports that the reference/DOIs/GEO fields were not saved properly on a recently uploaded record. They were visible in the web form when uploaded, but were then not displayed in the finished record.

This is exacerbated by https://github.com/VariantEffect/mavedb-ui/issues/41 because it's not possible to go back and edit the record to add the information in after the fact.

**Comment by jstone-uw** [comment]
I haven't been able to reproduce this with the current version, and I suggest we keep an eye on it and close the issue when we're confident that it has been resolved.

**Comment by afrubin** [comment]
We have another user who is experiencing this issue (for the DOI and raw reads fields) so I think we should keep investigating. It might be that things are failing to validate and not generating an error?

**Comment by ashsny** [comment]
fixed by https://github.com/VariantEffect/mavedb-ui/pull/124
