### ISSUE TITLE
Possible to add an invalid target

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#66]
When adding a new target, it's possible to add one that isn't valid (e.g. doesn't have the target type selected). The target type should be ideally be validated (at least to make sure all required fields are set) when the "add target" button is clicked in the UI.

**Comment by nickzoic** [comment]
I added some notes about this but in the wrong repo: https://github.com/VariantEffect/mavedb-api/issues/113 ... so I'll close that one.

**Comment by bencap** [comment]
Should be addressed by #214.

**Comment by bencap** [comment]
Closing, will be addressed by #214.
