### ISSUE TITLE
Updating permitted data licenses

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-ui#74]
The MaveDB project is committed to open data, so we should only allow open data licenses. This excludes the old default (and current option) CC-BY-NC-SA license.

A full list of open licenses can be found [here](http://opendefinition.org/licenses/).

It makes sense for us to stick with Creative Commons options, since we are licensing the individual records rather than the whole database. The available options after this update should be:
* CC0 1.0 [link](https://creativecommons.org/publicdomain/zero/1.0/) - default
* CC-BY 4.0 [link](https://creativecommons.org/licenses/by/4.0/)
* CC-BY-SA 4.0 [link](https://creativecommons.org/licenses/by-sa/4.0/)

Note this also means we should remove the "other" option, although it's fine to retain the data usage requirements text box.

**Comment by afrubin** [comment]
We still have a couple of datasets using the old CC-BY-NC-SA 4.0 license and will have to decide what to do with these. I will attempt to recontact the authors and see if they're OK with us relicensing to one of the open licenses.

**Comment by bencap** [comment]
Other licenses can remain in the DB, but should not be selectable (via API or UI).
