### ISSUE TITLE
Deprecated scoresets showing in searches

### ISSUE THREAD

**Issue by ashsny** [VariantEffect/mavedb-ui#75]
The documentation implies that deprecated scoresets should not show in searches. I assume this is captured by the `replaces_id` field/relationship in the scoresets table. However, https://mavedb.org/#/score-sets/urn:mavedb:00000005-a-1, for example, appears in search results, though it is replaced by https://mavedb.org/#/score-sets/urn:mavedb:00000005-a-4 and there is no indication on either score set page reflecting this relationship.

**Comment by EstelleDa** [comment]
@afrubin Double check with you. Do we only show the current newest score set in current version or both superseded and current version of score sets in viewing score set page? I remember there were both of them. 
Currently only superseded score set ID that's called `replaces_id` is saved in local database. However, both `superseded_score_set_urn` and `superseding_score_set_urn` are in Class `SavedScoreSet` in score set view_model. 

<img width="412" alt="image" src="https://github.com/VariantEffect/mavedb-ui/assets/8445097/88c51b08-1072-4fe1-89cc-c2c2b15bae14">

**Comment by afrubin** [comment]
Yeah we should only show the most current version in search. 

Deprecated score sets should only be accessible if someone goes to the URL directly, not via the web interface. They should also probably be excluded from the list of score sets in the api. 

I think it’s fine if the current score set doesn’t store information about what score set it’s replacing.

**Comment by EstelleDa** [comment]
I need time to think how to achieve it. They're still included in the list of score sets. Currently only Search results exclude them.
